package com.bw.health.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.health.bean.LoginBean;
import com.bw.health.bean.RemenBean;

import com.bw.health.dao.LoginBeanDao;
import com.bw.health.dao.RemenBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginBeanDaoConfig;
    private final DaoConfig remenBeanDaoConfig;

    private final LoginBeanDao loginBeanDao;
    private final RemenBeanDao remenBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginBeanDaoConfig = daoConfigMap.get(LoginBeanDao.class).clone();
        loginBeanDaoConfig.initIdentityScope(type);

        remenBeanDaoConfig = daoConfigMap.get(RemenBeanDao.class).clone();
        remenBeanDaoConfig.initIdentityScope(type);

        loginBeanDao = new LoginBeanDao(loginBeanDaoConfig, this);
        remenBeanDao = new RemenBeanDao(remenBeanDaoConfig, this);

        registerDao(LoginBean.class, loginBeanDao);
        registerDao(RemenBean.class, remenBeanDao);
    }
    
    public void clear() {
        loginBeanDaoConfig.clearIdentityScope();
        remenBeanDaoConfig.clearIdentityScope();
    }

    public LoginBeanDao getLoginBeanDao() {
        return loginBeanDao;
    }

    public RemenBeanDao getRemenBeanDao() {
        return remenBeanDao;
    }

}
